### ISSUE TITLE
Memory leak warning with Leakcanary

### ISSUE THREAD

**Issue by tuhin10** [generic-leo/SimpleArcLoader#3]
Hi,
Nice library. I am getting memory leak warning by leakcanary in SimpleArcLoader
![Uploading Screenshot_2016-02-02-15-43-15.png…]()

**Comment by tuhin10** [comment]
![screenshot_2016-02-02-15-43-15](https://cloud.githubusercontent.com/assets/11805182/12746449/b3c3c412-c9c4-11e5-85a2-df4a83f54988.png)

**Comment by prathameshsawant9** [comment]
Hi,
can you please share the code .. i can try and solve the issue ..

**Comment by tuhin10** [comment]
```
<com.leo.simplearcloader.SimpleArcLoader
                        android:visibility="gone"
                        android:id="@+id/arc_loader"
                        android:layout_gravity="center"
                        android:gravity="center"
                        android:layout_width="26dp"
                        android:layout_height="26dp"
                        custom:arc_thickness="2dp"
                        custom:arc_colors="@array/colors"
                        custom:arc_speed="medium"
                        custom:arc_margin="3dp" />
```

**Comment by tuhin10** [comment]
`SimpleArcLoader mArcLoader = (SimpleArcLoader) findViewById(R.id.arc_loader);
mArcLoader.setVisibility(View.VISIBLE); .`

**Comment by tuhin10** [comment]
Hey any fix for this?

**Comment by desugar-64** [comment]
I can confirm the memory leak too. ![Image of leak](https://sc-cdn.scaleengine.net/i/af4b6b7e2ed5f4f60428e659b6a748992.png)

**Comment by srujanb** [comment]
Yes even I am facing the issue of window leak. @sergeyfitis @tuhin10  guys, which app is that screenshot of?

**Comment by desugar-64** [comment]
@srujan7 Leak Canary https://github.com/square/leakcanary

**Comment by kraw4enko** [comment]
`protected void onVisibilityChanged (View view, int visibility) {
   super.onVisibilityChanged(view, visibility);
   if(visibility == VISIBLE){
      start();
   }else{
      stop();
   }
}`

**Comment by Nodjo** [comment]
There's an easy workaround which is to call SimpleArcLoader.stop() when done using it

**Comment by prathameshsawant9** [comment]
I have fixed this issue in the latest commit. @Nodjo Thanks for providing a workaround for the time being ! 👍
